#docker-compose.dev.yml (Extended config for DEVELOPMENT env.)
version: '3'

services:
  service_validator_tcoo:
    command: npm run start-dev
    environment:
      - NODE_ENV=development
      - PROFILE_ACTIVE=dev
      - ENDPOINT_SPRING_CLOUD_SERVER=http://172.21.0.194:8888
    volumes:
      - ./logs:/opt/medios_de_pago/logs