#docker-compose.prod.yml (Extended config for PRODUCTION env.)
version: '3'

services:
  service_validator_tcoo:
    command: npm start
    environment:
      - NODE_ENV=production
      - PROFILE_ACTIVE=prod
      - ENDPOINT_SPRING_CLOUD_SERVER=http://172.20.3.238:8888
    volumes:
      - /opt/medios_de_pago/logs:/opt/medios_de_pago/logs