version: '2'
services:
  iot_db_service:
    build: .
    network_mode: "host"
    restart: always
    volumes:
      -  /var/run/docker.sock:/tmp/docker.sock
    environment:
      - NODE_ENV=development
      - DB_NAME=home
      - DB_USER=postgres
      - DB_PASS=tony1983
      - DB_HOST=35.192.213.253
    container_name: iot_db_service